---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zk-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-0
  template:
    metadata:
      labels:
        app: zookeeper-0
    spec:
      containers:
      - name: zoo0
        image: digitalwonderland/zookeeper
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: zoo0
        - name: ZOOKEEPER_SERVER_2
          value: zoo1
        - name: ZOOKEEPER_SERVER_3
          value: zoo2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zk-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-1
  template:
    metadata:
      labels:
        app: zookeeper-1
    spec:
      containers:
      - name: zoo1
        image: digitalwonderland/zookeeper
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_ID
          value: "2"
        - name: ZOOKEEPER_SERVER_1
          value: zoo0
        - name: ZOOKEEPER_SERVER_2
          value: zoo1
        - name: ZOOKEEPER_SERVER_3
          value: zoo2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zk-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-2
  template:
    metadata:
      labels:
        app: zookeeper-2
    spec:
      containers:
      - name: zoo2
        image: digitalwonderland/zookeeper
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_ID
          value: "3"
        - name: ZOOKEEPER_SERVER_1
          value: zoo0
        - name: ZOOKEEPER_SERVER_2
          value: zoo1
        - name: ZOOKEEPER_SERVER_3
          value: zoo2